app:
  security:
    jwt:
      base64-secret: OTdiYTU1OTE1Y2E0ZjRjN2U0NTI2MTI2YjY4NDc4NjEwMWIyY2NmZGY4YTVjOTc0YzBmNDZlZDA5OGVlYmVlMzYzNGU3MTkyMjUzNGIzZGJlZjBhNmIzNGYzZWM1YmY5NjNhMzg4MTQyOTFhYTA0NGExNTNhNDBiZmRhNWNjZjA=
      token-validity-in-seconds: 8640000
      secret: 5BQ0aAFGyyTC7HVEUHic
    aws:
      credentials:
        access-key: "AKIAWJCGQ2JNB7LRYTOY"
        secret-key: "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"
      s3:
        region: "ap-southeast-3"
        bucket-name: "nle-backend-dev"
        access-key: "AKIAWJCGQ2JNAL4BLUZL"
        secret-key: "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"
    tax-ministry:
      api-key: "ae33fe80-8a30-49cf-bcc3-01aaa5aa8b4a"
    ftp:
      server: "ftp.nle-connect.id"
      path: "files"
      TRIGGER_URL: "http://54.169.71.70:8080/buildByToken/buildWithParameters?job=Update-FTP-User"
      TRIGGER_TOKEN: "sTbF18KYYkrr17CHhfpp"
  springdoc:
    name:  Nlebackend API
    url: http://api.nle-connect.id/
    email: non-reply@nle.com
    title: Nlebackend API
    description: Nlebackend API documentation
    version: 0.0.1
  url:
    active-url: https://api.nle-connect.id/api/activate/
    success-redirect-url: https://nle-connect.id/sign-in
    failed-redirect-url: https://nle-connect.id/sign-in
    impersonate-url: https://nle-connect.id/impersonate/token=
    tax-ministry: https://nlehub-dev.kemenkeu.go.id/DepoGate/Depo/post/data/depo-traffic
  scheduler:
    enabled: true
    ftp-sync-cron: 59 59 17 * * *
    tax-ministry-sync-cron: 59 59 23 * * *

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://210.247.245.143:3308/nlebackend?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: TXPSfYUiX9C4MmocXX0O
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
  forward-headers-strategy: framework

feign:
  client:
    config:
      jphServiceClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.nle.config.openfeign.TaxMinistryClientErrorDecoder
        retryer: com.nle.config.openfeign.TaxMinistryClientRetryer
