app:
  security:
    jwt:
      base64-secret: OTdiYTU1OTE1Y2E0ZjRjN2U0NTI2MTI2YjY4NDc4NjEwMWIyY2NmZGY4YTVjOTc0YzBmNDZlZDA5OGVlYmVlMzYzNGU3MTkyMjUzNGIzZGJlZjBhNmIzNGYzZWM1YmY5NjNhMzg4MTQyOTFhYTA0NGExNTNhNDBiZmRhNWNjZjA=
      token-validity-in-seconds: 86400
      secret: 5BQ0aAFGyyTC7HVEUHic
    aws:
      credentials:
        access-key: "AKIAWJCGQ2JNB7LRYTOY"
        secret-key: "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"
  springdoc:
    name:  Nlebackend API
    url: http://api.nle-connect.id/
    email: non-reply@nle.com
    title: Nlebackend API
    description: Nlebackend API documentation
    version: 0.0.1
  url:
    active-url: http://api.nle-connect.id/api/activate/
    success-redirect-url: http://nle-connect.id/sign-in
    failed-redirect-url: http://nle-connect.id/sign-in

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/nlebackend?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
server:
  port: 8080
