version: '3.8'
volumes:
  mysql_nle_data:
    driver: local
  elasticsearch_data:
    driver: local
services:
  mysql:
    image: mysql:8.0.28
    command:
      - --lower_case_table_names=1
    ports:
      - '3309:3306'
    environment:
      - MYSQL_DATABASE=nlebackend
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_nle_data:/var/lib/mysql/

  nle-backend:
    image: 'nlebackend:${VERSION}'
    ports:
      - '8083:8080'
    depends_on:
      - mysql
    labels:
      collect_logs_with_filebeat: 'true'
      decode_log_event_to_json_object: 'true'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - '9202:9200'
    environment:
      - 'discovery.type=single-node'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw # Persistence data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - '25828:25826'
      - '5046:5044'
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - '5603:5601'
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:rw # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # Additional information about containers
      - ./filebeat/data:/usr/share/filebeat/data:rw # Persistence data
    user: root # Allow access to log files and docker.sock
    restart: on-failure
    command:
      - '-e'
      - '--strict.perms=false'
    depends_on:
      - logstash
