version: '3.8'
volumes:
  mysql_nle_data:
    driver: local
services:
  mysql:
    image: mysql:8.0.28
    command:
      - --lower_case_table_names=1
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=nlebackend
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_nle_data:/var/lib/mysql/

  nle-backend:
    image: 'nlebackend:${VERSION}'
    ports:
      - '9999:8080'
    depends_on:
      - mysql
